name: clothing
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1
  shared_preferences: ^2.5.5
  random_string: ^2.3.1
  curved_navigation_bar: ^1.0.6
  google_fonts: ^8.1.0
  razorpay_flutter: ^1.4.5
  flutter_dotenv: ^6.0.1
  intl: ^0.20.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  image_picker: ^1.2.2
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/App_logo.jpeg"

flutter:
  uses-material-design: true

  assets:
    - .env
    - images/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/InterSemiBold.ttf